In [ ]:
Imagine you're a teacher.

You have marks of 1,000 students.

Now a new student comes.

Can you predict whether they'll pass or fail?
Or can you predict what marks they'll score?

Instead of predicting manually, you want the computer to learn from the previous 1,000 students and make predictions.

This process is called: Machine Learning

And the library that helps us do this in Python is: Scikit-learn

In [ ]:
Scikit-learn is an open-source Python library used to:

Build Machine Learning models
Train models
Test models
Make predictions
Evaluate model performance
Preprocess data

It provides ready-made implementations of common ML algorithms.

OR

Scikit-learn is an open-source Python library used for building, training, evaluating, and deploying Machine Learning models. It provides implementations of many supervised and unsupervised learning algorithms along with preprocessing and model evaluation tools.  

In [ ]:
Real-Life Example

Suppose a bank has data like:

Age	Salary	Loan Approved
25	30000	Yes
40	70000	Yes
19	12000	No
35	50000	Yes

A new customer arrives:
Age = 30
Salary = 45000

Question: Should the bank approve the loan?

Instead of writing hundreds of rules manually, we let a machine learning model learn from historical data and predict the answer.
Scikit-learn helps us build that model.

In [ ]:
Why Do We Need Scikit-learn?

Without Scikit-learn: 
You would have to write:
    
Linear Regression
Decision Tree
Random Forest
Logistic Regression

from scratch.

That could take thousands of lines of code.

With Scikit-learn:

from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X, y)

Just a few lines.   

In [ ]:
Scikit-learn Workflow ⭐⭐⭐⭐⭐

Every ML project follows almost the same workflow.

Collect Data
      ↓
Load Dataset
      ↓
Clean Data
      ↓
Split Data
      ↓
Train Model
      ↓
Test Model
      ↓
Evaluate
      ↓
Predict

In [ ]:
Technical Terms

Dataset: A collection of data.

Example:
Hours	Marks
2	     30
4	     55
6	     75

Feature (X): Input.
Example:
Study Hours

Target (y): Output.
Example:
Marks

Model: The algorithm after it has learned from the data.

Training: Teaching the model using existing data.

Prediction: Using the trained model to make predictions for new data.

In [ ]:
Q1. What is X?
Features (input variables).

Q2. What is y?
Target (output variable).

Q3. Why is X usually 2D?
Because Scikit-learn expects data in:
Rows × Columns
format.

Q4. Difference between Feature and Target?
Feature (X)	Target (y)
Input	Output
Known	Predicted

In [1]:
import pandas as pd

data = {
    "Hours": [2, 4, 6, 8],
    "Attendance": [80, 85, 90, 95],
    "Assignments": [5, 7, 9, 10],
    "Marks": [40, 60, 80, 95]
}

df = pd.DataFrame(data)

print(df)

   Hours  Attendance  Assignments  Marks
0      2          80            5     40
1      4          85            7     60
2      6          90            9     80
3      8          95           10     95


In [2]:
x = df[["Hours","Attendance","Assignments"]]
print(x)  # Feature (X) - Input,Known

# Why is X usually 2D?
# Because Scikit-learn expects data in:
# Rows × Columns 
# format.

   Hours  Attendance  Assignments
0      2          80            5
1      4          85            7
2      6          90            9
3      8          95           10


In [4]:
y=df["Marks"]
print(y)  #Target (y) - Output,Predicted

0    40
1    60
2    80
3    95
Name: Marks, dtype: int64


In [ ]:
Dataset is divided into:
1. Training Data: Used to teach the model.
2. Testing Data: Used to evaluate how well the model performs on unseen data.

Suppose we have student data:

Hours	Marks
2	40
4	60
6	80
8	95

If we train the model on ALL rows...

...and then ask it to predict the same rows...

Of course it will perform well.

That doesn't prove the model can predict new data.

In [ ]:
Example
Suppose we have:
1000 Records

Usually:
800 → Training (80%)
200 → Testing (20%)

Visual Understanding

1000 Students
│
├── 800 → Learn
│
└── 200 → Test

The model never sees those 200 records during training.

In [8]:
import pandas as pd
from sklearn.model_selection import train_test_split

data = {
    "Hours": [2, 4, 6, 8, 5, 7, 3, 9],
    "Attendance": [80, 85, 90, 95, 88, 92, 82, 97],
    "Marks": [40, 60, 80, 95, 70, 90, 50, 98]
}

df = pd.DataFrame(data)

x=df[["Hours","Attendance"]]
y=df["Marks"]

X_train,X_test,Y_train,Y_test = train_test_split(
    x,
    y,
    test_size = 0.2,  # means Testing data 20%
    random_state = 33 # can write anything
)

print(X_train)
print("----------------------------")
print(X_test)
print("----------------------------")
print(Y_train)
print("----------------------------")
print(Y_test)

   Hours  Attendance
3      8          95
1      4          85
5      7          92
2      6          90
0      2          80
4      5          88
----------------------------
   Hours  Attendance
6      3          82
7      9          97
----------------------------
3    95
1    60
5    90
2    80
0    40
4    70
Name: Marks, dtype: int64
----------------------------
6    50
7    98
Name: Marks, dtype: int64


In [ ]:
Why Random?

Suppose dataset:

1
2
3
4
5
6
7
8
9
10

Every time we split...

Different rows may be selected.

Example:

Run 1
Train:
1 2 3 5 6 8 9 10
Test:
4 7

Run 2
Train:
2 3 4 5 6 7 9 10
Test:
1 8

Different every time.

random_state fixes this.
random_state=42
Means:
Use the same random split every run.

In [ ]:
What is Overfitting?
-> When a model memorizes training data instead of learning general patterns, causing poor performance on new data.

In [ ]:
Feature Scaling
Feature Scaling is the process of transforming numerical features into a similar range so that no single feature dominates the learning process.

Why Is It Needed?
Imagine calculating distance.

Point A:
Age = 20
Salary = 25000

Point B:
Age = 21
Salary = 70000

Difference:
Age:
1

Salary:
45000

The algorithm mostly "sees" the salary difference.

Age has almost no influence.

Scaling fixes this.

In [ ]:
Which Algorithms Need Scaling? --> Very important interview question.

Need Scaling
✅ KNN

✅ SVM

✅ Logistic Regression

✅ Linear Regression (recommended)

✅ Neural Networks

✅ K-Means

Do NOT Need Scaling
✅ Decision Tree

✅ Random Forest

These algorithms split data based on conditions, not distances.

In [ ]:
Two Main Scaling Techniques : 

1. StandardScaler (Standardization) - Most commonly used
It transforms data so that:
Mean = 0
Standard Deviation = 1

Example
Before:
20
25
30
35
40

After:
-1.41
-0.70
0.00
0.70
1.41

Notice:
Values are centered around 0.


    
2. MinMaxScaler (Normalization)
Instead of centering around 0...
It converts everything between: 0 and 1

Example
Before:
20
25
30
35
40

After:
0.00
0.25
0.50
0.75
1.00

In [ ]:
StandardScaler vs MinMaxScaler

StandardScaler	              MinMaxScaler
Mean becomes 0	            Values between 0 and 1
Can have negative values	No negative values (default)
Most commonly used	        Good for bounded features

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)

X_test = scaler.transform(X_test)

In [ ]:
Why not fit_transform() on X_test?
Because: fit() should only learn from the training data.
For testing data: transform() uses the same scaling learned from the training set.
This prevents data leakage.

In fit_transform(),
fit() : Learns mean, standard deviation from your data.
transform(): Uses that information to scale the data.

In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

data = {
    "Age": [20,25,30,35,40],
    "Salary": [25000,35000,50000,65000,80000]
}

df = pd.DataFrame(data)

x= df[["Age"]]
y= df["Salary"]

X_train,X_test,Y_train,Y_test=train_test_split(
    x,
    y,
    test_size=0.2,
    random_state=42 
)

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

print(X_train)
print(X_test)

[[ 1.18321596]
 [-0.16903085]
 [-1.52127766]
 [ 0.50709255]]
[[-0.84515425]]


In [ ]:
Always remember this production workflow:

Dataset
      │
      ▼
Train-Test Split
      │
      ├──────────────┐
      ▼              ▼
X_train          X_test
      │              │
      ▼              │
fit_transform()      │
      │              │
      ▼              ▼
Scaled Train    transform()
                      │
                      ▼
                Scaled Test

In [ ]:
Encoding
Encoding is the process of converting categorical (text) data into numerical form so that machine learning algorithms can process it.
Because ML algorithms perform mathematical operations and cannot directly work with text values.

Types of Encoding
1. Label Encoding 
2. One-Hot Encoding 

In [ ]:
1. Label Encoding

Suppose:

Color
Red
Blue
Green

LabelEncoder converts them to numbers.

Example:
Red   → 2
Blue  → 0
Green → 1

Important: The exact numbers are assigned automatically and may differ depending on the data.

Code : 
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
df["Color"] = encoder.fit_transform(df["Color"])
print(df)

Output might be:

Color
2
0
1

How It Works
encoder = LabelEncoder() : Creates the encoder.

fit_transform() : fit() Learn the unique categories.

transform() : Convert them into numbers.

Problem with Label Encoding 
Suppose:
Red   → 0
Blue  → 1
Green → 2

The ML model may think: Green > Blue > Red
But...
Is Green greater than Blue?
❌ No.

Colors have no natural order.This creates a false relationship.

When to Use Label Encoding?
Use it only when the categories have a real order.

Example:

Education
School
College
Master's
PhD

Encoding:

School   → 0
College  → 1
Master's → 2
PhD      → 3

This order makes sense.

In [ ]:
2. One-Hot Encoding

Instead of giving numbers... 

Create separate columns.

Example:

Color
Red
Blue
Green

Becomes:

Red	Blue Green
1	 0	  0
0	 1	  0
0	 0	  1

No order is created.

Code : 
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder()
encoded = encoder.fit_transform(df[["Color"]])

Notice:
df[["Color"]]
Double brackets because OneHotEncoder expects 2D input.

In [ ]:
When should you use Label Encoding?
-> When the categories have a meaningful order (ordinal data).

When should you use One-Hot Encoding?
-> When categories are unordered (nominal data).

In [12]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

data = {
    "Gender": ["Male", "Female", "Female", "Male"],
    "Department": ["IT", "HR", "Finance", "IT"],
    "Salary": [50000, 40000, 45000, 60000]
}

df = pd.DataFrame(data)

encoder = OneHotEncoder()

encoded = encoder.fit_transform(df[["Gender","Department"]])

print(encoded)
print()
# print(encoded) - Why did print(encoded) not show the actual values?
# Expected answer:
# "Because OneHotEncoder returns a sparse matrix by default to save memory. To view the values, I can use .toarray() or convert it into a Pandas DataFrame."
# Example : print(encoded.toarray()) 

print(encoded.toarray())

# In modern Scikit-learn (v1.2+), there's an even cleaner approach:
# encoder = OneHotEncoder(sparse_output=False)
# Now encoded is already a NumPy array, so you don't need .toarray().

print()
encoded_df = pd.DataFrame(
    encoded.toarray(),
    columns=encoder.get_feature_names_out()
)

final_df = pd.concat([encoded_df,df["Salary"]],axis=1)
print(final_df)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 8 stored elements and shape (4, 5)>
  Coords	Values
  (0, 1)	1.0
  (0, 4)	1.0
  (1, 0)	1.0
  (1, 3)	1.0
  (2, 0)	1.0
  (2, 2)	1.0
  (3, 1)	1.0
  (3, 4)	1.0

[[0. 1. 0. 0. 1.]
 [1. 0. 0. 1. 0.]
 [1. 0. 1. 0. 0.]
 [0. 1. 0. 0. 1.]]

   Gender_Female  Gender_Male  Department_Finance  Department_HR  \
0            0.0          1.0                 0.0            0.0   
1            1.0          0.0                 0.0            1.0   
2            1.0          0.0                 1.0            0.0   
3            0.0          1.0                 0.0            0.0   

   Department_IT  Salary  
0            1.0   50000  
1            0.0   40000  
2            0.0   45000  
3            1.0   60000  


In [ ]:
Missing Value Handling (SimpleImputer)
Almost every real-world dataset contains missing values. If you don't handle them, most ML algorithms will throw an error.

Example: 
Imagine you're a teacher. You have this data:

Student	Hours	Marks
Rahul	  2	     40
Priya	  4	     60
Amit	 ❓	     80
Neha	  8	     95

Question:

Should we train our model?
❌ No.
Because one value is missing.

The ML model asks:
"How many hours did Amit study?"


What are Missing Values?
-> Missing values are data that is unavailable or not recorded.
-> In Python/Pandas, they are usually represented as: NaN - Not a Number

If we ignore it then Many Scikit-learn algorithms produce an error like: Input contains NaN.

There are two common approaches:
1. Delete Missing Values - If only a few rows are missing.
2. Fill Missing Values
-> Instead of deleting Replace missing values with a reasonable estimate. 
   This process is called Imputation

In [ ]:
Scikit-learn Tool: SimpleImputer

Methods of Filling Missing Values
1. Mean - Replace missing value with the average.
    
2. Median - Replace with the middle value. Median is often better when there are outliers.
    
3. Most Frequent 
-> For categorical data.
Example:

Male
Female
Male
NaN
Male

Most frequent: Male
Replace: NaN → Male

In [17]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer

data = {
    "Age": [20, np.nan, 30, 35, 40],
    "Salary": [25000, 30000, np.nan, 50000, 60000],
    "Gender": ["Male", "Female", np.nan, "Male", "Female"]
}

df = pd.DataFrame(data)

imputer1 = SimpleImputer(strategy="mean")
imputer2 = SimpleImputer(strategy="median")
imputer3 = SimpleImputer(strategy="most_frequent")

df["Age"] = imputer1.fit_transform(df[["Age"]])
df["Salary"] = imputer2.fit_transform(df[["Salary"]])
df["Gender"] = imputer3.fit_transform(df[["Gender"]]).ravel() # ravel() - converts 2d to 1d

print(df)

     Age   Salary  Gender
0  20.00  25000.0    Male
1  31.25  30000.0  Female
2  30.00  40000.0  Female
3  35.00  50000.0    Male
4  40.00  60000.0  Female
